<a href="https://colab.research.google.com/github/jerishobed/datascience/blob/master/Day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
a=5
a

5

In [4]:
import numpy as np

In [5]:
np.array([1,2])

array([1, 2])

In [6]:
a=np.array([1,2,3,4,5])
a


array([1, 2, 3, 4, 5])

In [9]:
matrix1=[[1,2],[3,4]]
np.array(matrix1)

array([[1, 2],
       [3, 4]])

Built in methods


In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(1,100,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])